<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["id" => 2, "name" => "اردبيل", "province_id" => 1],
            ["id" => 3, "name" => "اصلاندوز", "province_id" => 1],
            ["id" => 4, "name" => "آبي بيگلو", "province_id" => 1],
            ["id" => 5, "name" => "بيله سوار", "province_id" => 1],
            ["id" => 6, "name" => "پارس آباد", "province_id" => 1],
            ["id" => 7, "name" => "تازه كند", "province_id" => 1],
            ["id" => 8, "name" => "تازه كندانگوت", "province_id" => 1],
            ["id" => 9, "name" => "جعفرآباد", "province_id" => 1],
            ["id" => 10, "name" => "خلخال", "province_id" => 1],
            ["id" => 11, "name" => "رضي", "province_id" => 1],
            ["id" => 12, "name" => "سرعين", "province_id" => 1],
            ["id" => 13, "name" => "عنبران", "province_id" => 1],
            ["id" => 14, "name" => "فخرآباد", "province_id" => 1],
            ["id" => 15, "name" => "كلور", "province_id" => 1],
            ["id" => 16, "name" => "كوراييم", "province_id" => 1],
            ["id" => 17, "name" => "گرمي", "province_id" => 1],
            ["id" => 18, "name" => "گيوي", "province_id" => 1],
            ["id" => 19, "name" => "لاهرود", "province_id" => 1],
            ["id" => 20, "name" => "مرادلو", "province_id" => 1],
            ["id" => 21, "name" => "مشگين شهر", "province_id" => 1],
            ["id" => 22, "name" => "نمين", "province_id" => 1],
            ["id" => 23, "name" => "نير", "province_id" => 1],
            ["id" => 24, "name" => "هشتجين", "province_id" => 1],
            ["id" => 25, "name" => "هير", "province_id" => 1],

            ["id" => 26, "name" => "ابريشم", "province_id" => 2],
            ["id" => 27, "name" => "ابوزيدآباد", "province_id" => 2],
            ["id" => 28, "name" => "اردستان", "province_id" => 2],
            ["id" => 29, "name" => "اژيه", "province_id" => 2],
            ["id" => 30, "name" => "اصفهان", "province_id" => 2],
            ["id" => 31, "name" => "افوس", "province_id" => 2],
            ["id" => 32, "name" => "انارک", "province_id" => 2],
            ["id" => 33, "name" => "ايمانشهر", "province_id" => 2],
            ["id" => 34, "name" => "آران وبيدگل", "province_id" => 2],
            ["id" => 35, "name" => "بادرود", "province_id" => 2],
            ["id" => 36, "name" => "باغ بهادران", "province_id" => 2],
            ["id" => 37, "name" => "بافران", "province_id" => 2],
            ["id" => 38, "name" => "برزك", "province_id" => 2],
            ["id" => 39, "name" => "برف انبار", "province_id" => 2],
            ["id" => 40, "name" => "بوئين ومياندشت", "province_id" => 2],
            ["id" => 41, "name" => "بهاران شهر", "province_id" => 2],
            ["id" => 42, "name" => "بهارستان", "province_id" => 2],
            ["id" => 43, "name" => "پيربكران", "province_id" => 2],
            ["id" => 44, "name" => "تودشك", "province_id" => 2],
            ["id" => 45, "name" => "تيران", "province_id" => 2],
            ["id" => 46, "name" => "جندق", "province_id" => 2],
            ["id" => 47, "name" => "جوزدان", "province_id" => 2],
            ["id" => 48, "name" => "جوشقان وكامو", "province_id" => 2],
            ["id" => 49, "name" => "چادگان", "province_id" => 2],
            ["id" => 50, "name" => "چرمهين", "province_id" => 2],
            ["id" => 51, "name" => "چمگردان", "province_id" => 2],
            ["id" => 52, "name" => "حبيب آباد", "province_id" => 2],
            ["id" => 53, "name" => "حسن آباد", "province_id" => 2],
            ["id" => 54, "name" => "حنا", "province_id" => 2],
            ["id" => 55, "name" => "خالدآباد", "province_id" => 2],
            ["id" => 56, "name" => "خميني شهر", "province_id" => 2],
            ["id" => 57, "name" => "خوانسار", "province_id" => 2],
            ["id" => 58, "name" => "خور", "province_id" => 2],
            ["id" => 59, "name" => "خوراسگان", "province_id" => 2],
            ["id" => 60, "name" => "خورزوق", "province_id" => 2],
            ["id" => 61, "name" => "داران", "province_id" => 2],
            ["id" => 62, "name" => "دامنه", "province_id" => 2],
            ["id" => 63, "name" => "درچه پياز", "province_id" => 2],
            ["id" => 64, "name" => "دستگرد", "province_id" => 2],
            ["id" => 65, "name" => "دولت آباد", "province_id" => 2],
            ["id" => 66, "name" => "دهاقان", "province_id" => 2],
            ["id" => 67, "name" => "دهق", "province_id" => 2],
            ["id" => 68, "name" => "ديزيچه", "province_id" => 2],
            ["id" => 69, "name" => "رزوه", "province_id" => 2],
            ["id" => 70, "name" => "رضوانشهر", "province_id" => 2],
            ["id" => 71, "name" => "زاينده رود", "province_id" => 2],
            ["id" => 72, "name" => "زرين شهر", "province_id" => 2],
            ["id" => 73, "name" => "زواره", "province_id" => 2],
            ["id" => 74, "name" => "زيباشهر", "province_id" => 2],
            ["id" => 75, "name" => "سده لنجان", "province_id" => 2],
            ["id" => 76, "name" => "سفيدشهر", "province_id" => 2],
            ["id" => 77, "name" => "سگزي", "province_id" => 2],
            ["id" => 78, "name" => "سميرم", "province_id" => 2],
            ["id" => 79, "name" => "شاپورآباد", "province_id" => 2],
            ["id" => 80, "name" => "شاهين شهر", "province_id" => 2],
            ["id" => 81, "name" => "شهرضا", "province_id" => 2],
            ["id" => 82, "name" => "طالخونچه", "province_id" => 2],
            ["id" => 83, "name" => "عسگران", "province_id" => 2],
            ["id" => 84, "name" => "علويچه", "province_id" => 2],
            ["id" => 85, "name" => "فرخي", "province_id" => 2],
            ["id" => 86, "name" => "فريدونشهر", "province_id" => 2],
            ["id" => 87, "name" => "فلاورجان", "province_id" => 2],
            ["id" => 88, "name" => "فولادشهر", "province_id" => 2],
            ["id" => 89, "name" => "قمصر", "province_id" => 2],
            ["id" => 90, "name" => "قهجاورستان", "province_id" => 2],
            ["id" => 91, "name" => "قهدريجان", "province_id" => 2],
            ["id" => 92, "name" => "كاشان", "province_id" => 2],
            ["id" => 93, "name" => "كركوند", "province_id" => 2],
            ["id" => 94, "name" => "كليشادوسودرجان", "province_id" => 2],
            ["id" => 95, "name" => "كمشچه", "province_id" => 2],
            ["id" => 96, "name" => "كمه", "province_id" => 2],
            ["id" => 97, "name" => "كوشك", "province_id" => 2],
            ["id" => 98, "name" => "كوهپايه", "province_id" => 2],
            ["id" => 99, "name" => "كهريزسنگ", "province_id" => 2],
            ["id" => 100, "name" => "گرگاب", "province_id" => 2],
            ["id" => 101, "name" => "گزبرخوار", "province_id" => 2],
            ["id" => 102, "name" => "گلپايگان", "province_id" => 2],
            ["id" => 103, "name" => "گلدشت", "province_id" => 2],
            ["id" => 104, "name" => "گلشن", "province_id" => 2],
            ["id" => 105, "name" => "گلشهر", "province_id" => 2],
            ["id" => 106, "name" => "گوگد", "province_id" => 2],
            ["id" => 107, "name" => "لاي بيد", "province_id" => 2],
            ["id" => 108, "name" => "مباركه", "province_id" => 2],
            ["id" => 109, "name" => "محمدآباد", "province_id" => 2],
            ["id" => 110, "name" => "مشكات", "province_id" => 2],
            ["id" => 111, "name" => "منظريه", "province_id" => 2],
            ["id" => 112, "name" => "مهاباد", "province_id" => 2],
            ["id" => 113, "name" => "ميمه", "province_id" => 2],
            ["id" => 114, "name" => "نائين", "province_id" => 2],
            ["id" => 115, "name" => "نجف آباد", "province_id" => 2],
            ["id" => 116, "name" => "نصرآباد", "province_id" => 2],
            ["id" => 117, "name" => "نطنز", "province_id" => 2],
            ["id" => 118, "name" => "نوش آباد", "province_id" => 2],
            ["id" => 119, "name" => "نياسر", "province_id" => 2],
            ["id" => 120, "name" => "نيك آباد", "province_id" => 2],
            ["id" => 121, "name" => "ورزنه", "province_id" => 2],
            ["id" => 122, "name" => "ورنامخواست", "province_id" => 2],
            ["id" => 123, "name" => "وزوان", "province_id" => 2],
            ["id" => 124, "name" => "ونك", "province_id" => 2],
            ["id" => 125, "name" => "هرند", "province_id" => 2],
            ["id" => 126, "name" => "اشتهارد", "province_id" => 3],
            ["id" => 127, "name" => "آسارا", "province_id" => 3],
            ["id" => 128, "name" => "تنكمان", "province_id" => 3],
            ["id" => 129, "name" => "چهارباغ", "province_id" => 3],
            ["id" => 130, "name" => "سيف آباد", "province_id" => 3],
            ["id" => 131, "name" => "شهرجديدهشتگرد", "province_id" => 3],
            ["id" => 132, "name" => "طالقان", "province_id" => 3],
            ["id" => 133, "name" => "كرج", "province_id" => 3],
            ["id" => 134, "name" => "كمال شهر", "province_id" => 3],
            ["id" => 135, "name" => "كوهسار", "province_id" => 3],
            ["id" => 136, "name" => "گرمدره", "province_id" => 3],
            ["id" => 137, "name" => "ماهدشت", "province_id" => 3],
            ["id" => 138, "name" => "محمدشهر", "province_id" => 3],
            ["id" => 139, "name" => "مشكين دشت", "province_id" => 3],
            ["id" => 140, "name" => "نظرآباد", "province_id" => 3],
            ["id" => 141, "name" => "هشتگرد", "province_id" => 3],
            ["id" => 142, "name" => "اركواز", "province_id" => 4],
            ["id" => 143, "name" => "ايلام", "province_id" => 4],
            ["id" => 144, "name" => "ايوان", "province_id" => 4],
            ["id" => 145, "name" => "آبدانان", "province_id" => 4],
            ["id" => 146, "name" => "آسمان آباد", "province_id" => 4],
            ["id" => 147, "name" => "بدره", "province_id" => 4],
            ["id" => 148, "name" => "پهله", "province_id" => 4],
            ["id" => 149, "name" => "توحيد", "province_id" => 4],
            ["id" => 150, "name" => "چوار", "province_id" => 4],
            ["id" => 151, "name" => "دره شهر", "province_id" => 4],
            ["id" => 152, "name" => "دلگشا", "province_id" => 4],
            ["id" => 153, "name" => "دهلران", "province_id" => 4],
            ["id" => 154, "name" => "زرنه", "province_id" => 4],
            ["id" => 155, "name" => "سراب باغ", "province_id" => 4],
            ["id" => 156, "name" => "سرابله", "province_id" => 4],
            ["id" => 157, "name" => "صالح آباد", "province_id" => 4],
            ["id" => 158, "name" => "لومار", "province_id" => 4],
            ["id" => 159, "name" => "مورموري", "province_id" => 4],
            ["id" => 160, "name" => "موسيان", "province_id" => 4],
            ["id" => 161, "name" => "مهران", "province_id" => 4],
            ["id" => 162, "name" => "ميمه", "province_id" => 4],
            ["id" => 163, "name" => "اسكو", "province_id" => 5],
            ["id" => 164, "name" => "اهر", "province_id" => 5],
            ["id" => 165, "name" => "ايلخچي", "province_id" => 5],
            ["id" => 166, "name" => "آبش احمد", "province_id" => 5],
            ["id" => 167, "name" => "آذرشهر", "province_id" => 5],
            ["id" => 168, "name" => "آقكند", "province_id" => 5],
            ["id" => 169, "name" => "باسمنج", "province_id" => 5],
            ["id" => 170, "name" => "بخشايش", "province_id" => 5],
            ["id" => 171, "name" => "بستان آباد", "province_id" => 5],
            ["id" => 172, "name" => "بناب", "province_id" => 5],
            ["id" => 173, "name" => "بناب جديد", "province_id" => 5],
            ["id" => 174, "name" => "تبريز", "province_id" => 5],
            ["id" => 175, "name" => "ترک", "province_id" => 5],
            ["id" => 176, "name" => "تركمانچاي", "province_id" => 5],
            ["id" => 177, "name" => "تسوج", "province_id" => 5],
            ["id" => 178, "name" => "تيكمه داش", "province_id" => 5],
            ["id" => 179, "name" => "جلفا", "province_id" => 5],
            ["id" => 180, "name" => "خاروانا", "province_id" => 5],
            ["id" => 181, "name" => "خامنه", "province_id" => 5],
            ["id" => 182, "name" => "خراجو", "province_id" => 5],
            ["id" => 183, "name" => "خسروشهر", "province_id" => 5],
            ["id" => 184, "name" => "خمارلو", "province_id" => 5],
            ["id" => 185, "name" => "خواجه", "province_id" => 5],
            ["id" => 186, "name" => "دوزدوزان", "province_id" => 5],
            ["id" => 187, "name" => "زرنق", "province_id" => 5],
            ["id" => 188, "name" => "زنوز", "province_id" => 5],
            ["id" => 189, "name" => "سراب", "province_id" => 5],
            ["id" => 190, "name" => "سردرود", "province_id" => 5],
            ["id" => 191, "name" => "سيس", "province_id" => 5],
            ["id" => 192, "name" => "سيه رود", "province_id" => 5],
            ["id" => 193, "name" => "شبستر", "province_id" => 5],
            ["id" => 194, "name" => "شربيان", "province_id" => 5],
            ["id" => 195, "name" => "شرفخانه", "province_id" => 5],
            ["id" => 196, "name" => "شندآباد", "province_id" => 5],
            ["id" => 197, "name" => "شهرجديدسهند", "province_id" => 5],
            ["id" => 198, "name" => "صوفيان", "province_id" => 5],
            ["id" => 199, "name" => "عجب شير", "province_id" => 5],
            ["id" => 200, "name" => "قره آغاج", "province_id" => 5],
            ["id" => 201, "name" => "كشكسراي", "province_id" => 5],
            ["id" => 202, "name" => "كلوانق", "province_id" => 5],
            ["id" => 203, "name" => "كليبر", "province_id" => 5],
            ["id" => 204, "name" => "كوزه كنان", "province_id" => 5],
            ["id" => 205, "name" => "گوگان", "province_id" => 5],
            ["id" => 206, "name" => "ليلان", "province_id" => 5],
            ["id" => 207, "name" => "مراغه", "province_id" => 5],
            ["id" => 208, "name" => "مرند", "province_id" => 5],
            ["id" => 209, "name" => "ملكان", "province_id" => 5],
            ["id" => 210, "name" => "ممقان", "province_id" => 5],
            ["id" => 211, "name" => "مهربان", "province_id" => 5],
            ["id" => 212, "name" => "ميانه", "province_id" => 5],
            ["id" => 213, "name" => "نظركهريزي", "province_id" => 5],
            ["id" => 214, "name" => "وايقان", "province_id" => 5],
            ["id" => 215, "name" => "ورزقان", "province_id" => 5],
            ["id" => 216, "name" => "هاديشهر", "province_id" => 5],
            ["id" => 217, "name" => "هريس", "province_id" => 5],
            ["id" => 218, "name" => "هشترود", "province_id" => 5],
            ["id" => 219, "name" => "هوراند", "province_id" => 5],
            ["id" => 220, "name" => "يامچي", "province_id" => 5],

            ["id" => 221, "name" => "اروميه", "province_id" => 6],
            ["id" => 222, "name" => "اشنويه", "province_id" => 6],
            ["id" => 223, "name" => "ايواوغلي", "province_id" => 6],
            ["id" => 224, "name" => "آواجيق", "province_id" => 6],
            ["id" => 225, "name" => "باروق", "province_id" => 6],
            ["id" => 226, "name" => "بازرگان", "province_id" => 6],
            ["id" => 227, "name" => "بوكان", "province_id" => 6],
            ["id" => 228, "name" => "پلدشت", "province_id" => 6],
            ["id" => 229, "name" => "پيرانشهر", "province_id" => 6],
            ["id" => 230, "name" => "تازه شهر", "province_id" => 6],
            ["id" => 231, "name" => "تكاب", "province_id" => 6],
            ["id" => 232, "name" => "چهاربرج", "province_id" => 6],
            ["id" => 233, "name" => "خليفان", "province_id" => 6],
            ["id" => 234, "name" => "خوي", "province_id" => 6],
            ["id" => 235, "name" => "ديزج ديز", "province_id" => 6],
            ["id" => 236, "name" => "ربط", "province_id" => 6],
            ["id" => 237, "name" => "سردشت", "province_id" => 6],
            ["id" => 238, "name" => "سرو", "province_id" => 6],
            ["id" => 239, "name" => "سلماس", "province_id" => 6],
            ["id" => 240, "name" => "سيلوانه", "province_id" => 6],
            ["id" => 241, "name" => "سيمينه", "province_id" => 6],
            ["id" => 242, "name" => "سيه چشمه", "province_id" => 6],
            ["id" => 243, "name" => "شاهين دژ", "province_id" => 6],
            ["id" => 244, "name" => "شوط", "province_id" => 6],
            ["id" => 245, "name" => "فيرورق", "province_id" => 6],
            ["id" => 246, "name" => "قره ضياءالدين", "province_id" => 6],
            ["id" => 247, "name" => "قطور", "province_id" => 6],
            ["id" => 248, "name" => "قوشچي", "province_id" => 6],
            ["id" => 249, "name" => "كشاورز", "province_id" => 6],
            ["id" => 250, "name" => "گردكشانه", "province_id" => 6],
            ["id" => 251, "name" => "ماكو", "province_id" => 6],
            ["id" => 252, "name" => "محمديار", "province_id" => 6],
            ["id" => 253, "name" => "محمودآباد", "province_id" => 6],
            ["id" => 254, "name" => "مهاباد", "province_id" => 6],
            ["id" => 255, "name" => "مياندوآب", "province_id" => 6],
            ["id" => 256, "name" => "ميرآباد", "province_id" => 6],
            ["id" => 257, "name" => "نالوس", "province_id" => 6],
            ["id" => 258, "name" => "نقده", "province_id" => 6],
            ["id" => 259, "name" => "نوشين", "province_id" => 6],
            ["id" => 260, "name" => "امام حسن", "province_id" => 7],
            ["id" => 261, "name" => "انارستان", "province_id" => 7],
            ["id" => 262, "name" => "اهرم", "province_id" => 7],
            ["id" => 263, "name" => "آبپخش", "province_id" => 7],
            ["id" => 264, "name" => "آبدان", "province_id" => 7],
            ["id" => 265, "name" => "برازجان", "province_id" => 7],
            ["id" => 266, "name" => "بردخون", "province_id" => 7],
            ["id" => 267, "name" => "بردستان", "province_id" => 7],
            ["id" => 268, "name" => "بندردير", "province_id" => 7],
            ["id" => 269, "name" => "بندرديلم", "province_id" => 7],
            ["id" => 270, "name" => "بندرريگ", "province_id" => 7],
            ["id" => 271, "name" => "بندركنگان", "province_id" => 7],
            ["id" => 272, "name" => "بندرگناوه", "province_id" => 7],
            ["id" => 273, "name" => "بنک", "province_id" => 7],
            ["id" => 274, "name" => "بوشهر", "province_id" => 7],
            ["id" => 275, "name" => "تنگ ارم", "province_id" => 7],
            ["id" => 276, "name" => "جم", "province_id" => 7],
            ["id" => 277, "name" => "چغادک", "province_id" => 7],
            ["id" => 278, "name" => "خارک", "province_id" => 7],
            ["id" => 279, "name" => "خورموج", "province_id" => 7],
            ["id" => 280, "name" => "دالكي", "province_id" => 7],
            ["id" => 281, "name" => "دلوار", "province_id" => 7],
            ["id" => 282, "name" => "ريز", "province_id" => 7],
            ["id" => 283, "name" => "سعدآباد", "province_id" => 7],
            ["id" => 284, "name" => "سيراف", "province_id" => 7],
            ["id" => 285, "name" => "شبانكاره", "province_id" => 7],
            ["id" => 286, "name" => "شنبه", "province_id" => 7],
            ["id" => 287, "name" => "عسلويه", "province_id" => 7],
            ["id" => 288, "name" => "كاكي", "province_id" => 7],
            ["id" => 289, "name" => "كلمه", "province_id" => 7],
            ["id" => 290, "name" => "نخل تقي", "province_id" => 7],
            ["id" => 291, "name" => "وحدتيه", "province_id" => 7],

            ["id" => 292, "name" => "ارجمند", "province_id" => 8],
            ["id" => 293, "name" => "اسلامشهر", "province_id" => 8],
            ["id" => 294, "name" => "انديشه", "province_id" => 8],
            ["id" => 295, "name" => "آبسرد", "province_id" => 8],
            ["id" => 296, "name" => "آبعلي", "province_id" => 8],
            ["id" => 297, "name" => "باغستان", "province_id" => 8],
            ["id" => 298, "name" => "باقرشهر", "province_id" => 8],
            ["id" => 299, "name" => "بومهن", "province_id" => 8],
            ["id" => 300, "name" => "پاكدشت", "province_id" => 8],
            ["id" => 301, "name" => "پرديس", "province_id" => 8],
            ["id" => 302, "name" => "پيشوا", "province_id" => 8],
            ["id" => 303, "name" => "تجريش", "province_id" => 8],
            ["id" => 304, "name" => "تهران", "province_id" => 8],
            ["id" => 305, "name" => "جوادآباد", "province_id" => 8],
            ["id" => 306, "name" => "چهاردانگه", "province_id" => 8],
            ["id" => 307, "name" => "حسن آباد", "province_id" => 8],
            ["id" => 308, "name" => "دماوند", "province_id" => 8],
            ["id" => 309, "name" => "رباط کريم", "province_id" => 8],
            ["id" => 310, "name" => "رودهن", "province_id" => 8],
            ["id" => 311, "name" => "ري", "province_id" => 8],
            ["id" => 312, "name" => "شاهدشهر", "province_id" => 8],
            ["id" => 313, "name" => "شريف آباد", "province_id" => 8],
            ["id" => 314, "name" => "شهريار", "province_id" => 8],
            ["id" => 315, "name" => "صالح آباد", "province_id" => 8],
            ["id" => 316, "name" => "صباشهر", "province_id" => 8],
            ["id" => 317, "name" => "صفادشت", "province_id" => 8],
            ["id" => 318, "name" => "فردوسيه", "province_id" => 8],
            ["id" => 319, "name" => "فرون آباد", "province_id" => 8],
            ["id" => 320, "name" => "فشم", "province_id" => 8],
            ["id" => 321, "name" => "فيروزكوه", "province_id" => 8],
            ["id" => 322, "name" => "قدس", "province_id" => 8],
            ["id" => 323, "name" => "قرچک", "province_id" => 8],
            ["id" => 324, "name" => "كهريزک", "province_id" => 8],
            ["id" => 325, "name" => "كيلان", "province_id" => 8],
            ["id" => 326, "name" => "گلستان", "province_id" => 8],
            ["id" => 327, "name" => "لواسان", "province_id" => 8],
            ["id" => 328, "name" => "ملارد", "province_id" => 8],
            ["id" => 329, "name" => "نسيم شهر", "province_id" => 8],
            ["id" => 330, "name" => "نصيرآباد", "province_id" => 8],
            ["id" => 331, "name" => "وحيديه", "province_id" => 8],
            ["id" => 332, "name" => "ورامين", "province_id" => 8],
            ["id" => 333, "name" => "اردل", "province_id" => 9],
            ["id" => 334, "name" => "آلوني", "province_id" => 9],
            ["id" => 335, "name" => "باباحيدر", "province_id" => 9],
            ["id" => 336, "name" => "بروجن", "province_id" => 9],
            ["id" => 337, "name" => "بلداجي", "province_id" => 9],
            ["id" => 338, "name" => "بن", "province_id" => 9],
            ["id" => 339, "name" => "جونقان", "province_id" => 9],
            ["id" => 340, "name" => "چلگرد", "province_id" => 9],
            ["id" => 341, "name" => "سامان", "province_id" => 9],
            ["id" => 342, "name" => "سفيددشت", "province_id" => 9],
            ["id" => 343, "name" => "سودجان", "province_id" => 9],
            ["id" => 344, "name" => "سورشجان", "province_id" => 9],
            ["id" => 345, "name" => "شلمزار", "province_id" => 9],
            ["id" => 346, "name" => "شهركرد", "province_id" => 9],
            ["id" => 347, "name" => "طاقانک", "province_id" => 9],
            ["id" => 348, "name" => "فارسان", "province_id" => 9],
            ["id" => 349, "name" => "فرادنبه", "province_id" => 9],
            ["id" => 350, "name" => "فرخ شهر", "province_id" => 9],
            ["id" => 351, "name" => "كيان", "province_id" => 9],
            ["id" => 352, "name" => "گندمان", "province_id" => 9],
            ["id" => 353, "name" => "گهرو", "province_id" => 9],
            ["id" => 354, "name" => "لردگان", "province_id" => 9],
            ["id" => 355, "name" => "مال خليفه", "province_id" => 9],
            ["id" => 356, "name" => "ناغان", "province_id" => 9],
            ["id" => 357, "name" => "نافچ", "province_id" => 9],
            ["id" => 358, "name" => "نقنه", "province_id" => 9],
            ["id" => 359, "name" => "هفشجان", "province_id" => 9],
            ["id" => 360, "name" => "ارسک", "province_id" => 10],
            ["id" => 361, "name" => "اسديه", "province_id" => 10],
            ["id" => 362, "name" => "اسفدن", "province_id" => 10],
            ["id" => 363, "name" => "اسلاميه", "province_id" => 10],
            ["id" => 364, "name" => "آرين شهر", "province_id" => 10],
            ["id" => 365, "name" => "آيسک", "province_id" => 10],
            ["id" => 366, "name" => "بشرويه", "province_id" => 10],
            ["id" => 367, "name" => "بيرجند", "province_id" => 10],
            ["id" => 368, "name" => "حاجي آباد", "province_id" => 10],
            ["id" => 369, "name" => "خضري دشت بياض", "province_id" => 10],
            ["id" => 370, "name" => "خوسف", "province_id" => 10],
            ["id" => 371, "name" => "زهان", "province_id" => 10],
            ["id" => 372, "name" => "سرايان", "province_id" => 10],
            ["id" => 373, "name" => "سربيشه", "province_id" => 10],
            ["id" => 374, "name" => "سه قلعه", "province_id" => 10],
            ["id" => 375, "name" => "شوسف", "province_id" => 10],
            ["id" => 376, "name" => "طبس مسينا", "province_id" => 10],
            ["id" => 377, "name" => "فردوس", "province_id" => 10],
            ["id" => 378, "name" => "قائن", "province_id" => 10],
            ["id" => 379, "name" => "قهستان", "province_id" => 10],
            ["id" => 380, "name" => "گزيک", "province_id" => 10],
            ["id" => 381, "name" => "محمد شهر", "province_id" => 10],
            ["id" => 382, "name" => "مود", "province_id" => 10],
            ["id" => 383, "name" => "نهبندان", "province_id" => 10],
            ["id" => 384, "name" => "نيمبلوک", "province_id" => 10],
            ["id" => 385, "name" => "احمدآبادصولت", "province_id" => 11],
            ["id" => 386, "name" => "انابد", "province_id" => 11],
            ["id" => 387, "name" => "باجگيران", "province_id" => 11],
            ["id" => 388, "name" => "باخرز", "province_id" => 11],
            ["id" => 389, "name" => "بار", "province_id" => 11],
            ["id" => 390, "name" => "بايگ", "province_id" => 11],
            ["id" => 391, "name" => "بجستان", "province_id" => 11],
            ["id" => 392, "name" => "بردسكن", "province_id" => 11],
            ["id" => 393, "name" => "بيدخت", "province_id" => 11],
            ["id" => 394, "name" => "تايباد", "province_id" => 11],
            ["id" => 395, "name" => "تربت جام", "province_id" => 11],
            ["id" => 396, "name" => "تربت حيدريه", "province_id" => 11],
            ["id" => 397, "name" => "جغتاي", "province_id" => 11],
            ["id" => 398, "name" => "جنگل", "province_id" => 11],
            ["id" => 399, "name" => "چاپشلو", "province_id" => 11],
            ["id" => 400, "name" => "چكنه", "province_id" => 11],
            ["id" => 401, "name" => "چناران", "province_id" => 11],
            ["id" => 402, "name" => "خرو", "province_id" => 11],
            ["id" => 403, "name" => "خليل آباد", "province_id" => 11],
            ["id" => 404, "name" => "خواف", "province_id" => 11],
            ["id" => 405, "name" => "داورزن", "province_id" => 11],
            ["id" => 406, "name" => "درگز", "province_id" => 11],
            ["id" => 407, "name" => "درود", "province_id" => 11],
            ["id" => 408, "name" => "دولت آباد", "province_id" => 11],
            ["id" => 409, "name" => "رباط سنگ", "province_id" => 11],
            ["id" => 410, "name" => "رشتخوار", "province_id" => 11],
            ["id" => 411, "name" => "رضويه", "province_id" => 11],
            ["id" => 412, "name" => "روداب", "province_id" => 11],
            ["id" => 413, "name" => "ريوش", "province_id" => 11],
            ["id" => 414, "name" => "سبزوار", "province_id" => 11],
            ["id" => 415, "name" => "سرخس", "province_id" => 11],
            ["id" => 416, "name" => "سفيدسنگ", "province_id" => 11],
            ["id" => 417, "name" => "سلامي", "province_id" => 11],
            ["id" => 418, "name" => "سلطان آباد", "province_id" => 11],
            ["id" => 419, "name" => "سنگان", "province_id" => 11],
            ["id" => 420, "name" => "شادمهر", "province_id" => 11],
            ["id" => 421, "name" => "شانديز", "province_id" => 11],
            ["id" => 422, "name" => "ششتمد", "province_id" => 11],
            ["id" => 423, "name" => "شهرآباد", "province_id" => 11],
            ["id" => 424, "name" => "شهرزو", "province_id" => 11],
            ["id" => 425, "name" => "صالح آباد", "province_id" => 11],
            ["id" => 426, "name" => "طرقبه", "province_id" => 11],
            ["id" => 427, "name" => "عشق آباد", "province_id" => 11],
            ["id" => 428, "name" => "فرهادگرد", "province_id" => 11],
            ["id" => 429, "name" => "فريمان", "province_id" => 11],
            ["id" => 430, "name" => "فيروزه", "province_id" => 11],
            ["id" => 431, "name" => "فيض آباد", "province_id" => 11],
            ["id" => 432, "name" => "قاسم آباد", "province_id" => 11],
            ["id" => 433, "name" => "قدمگاه", "province_id" => 11],
            ["id" => 434, "name" => "قلندرآباد", "province_id" => 11],
            ["id" => 435, "name" => "قوچان", "province_id" => 11],
            ["id" => 436, "name" => "كاخک", "province_id" => 11],
            ["id" => 437, "name" => "كاريز", "province_id" => 11],
            ["id" => 438, "name" => "كاشمر", "province_id" => 11],
            ["id" => 439, "name" => "كدكن", "province_id" => 11],
            ["id" => 440, "name" => "كلات", "province_id" => 11],
            ["id" => 441, "name" => "كندر", "province_id" => 11],
            ["id" => 442, "name" => "گلمكان", "province_id" => 11],
            ["id" => 443, "name" => "گناباد", "province_id" => 11],
            ["id" => 444, "name" => "لطف آباد", "province_id" => 11],
            ["id" => 445, "name" => "مزدآوند", "province_id" => 11],
            ["id" => 446, "name" => "مشهد", "province_id" => 11],
            ["id" => 447, "name" => "مشهدريزه", "province_id" => 11],
            ["id" => 448, "name" => "ملك آباد", "province_id" => 11],
            ["id" => 449, "name" => "نشتيفان", "province_id" => 11],
            ["id" => 450, "name" => "نصر آباد", "province_id" => 11],
            ["id" => 451, "name" => "نقاب", "province_id" => 11],
            ["id" => 452, "name" => "نوخندان", "province_id" => 11],
            ["id" => 453, "name" => "نيشابور", "province_id" => 11],
            ["id" => 454, "name" => "نيل شهر", "province_id" => 11],
            ["id" => 455, "name" => "همت آباد", "province_id" => 11],
            ["id" => 456, "name" => "يونسی", "province_id" => 11],
            ["id" => 457, "name" => "اسفراين", "province_id" => 12],
            ["id" => 458, "name" => "ايور", "province_id" => 12],
            ["id" => 459, "name" => "آشخانه", "province_id" => 12],
            ["id" => 460, "name" => "بجنورد", "province_id" => 12],
            ["id" => 461, "name" => "پيش قلعه", "province_id" => 12],
            ["id" => 462, "name" => "تيتكانلو", "province_id" => 12],
            ["id" => 463, "name" => "جاجرم", "province_id" => 12],
            ["id" => 464, "name" => "حصارگرمخان", "province_id" => 12],
            ["id" => 465, "name" => "درق", "province_id" => 12],
            ["id" => 466, "name" => "راز", "province_id" => 12],
            ["id" => 467, "name" => "سنخواست", "province_id" => 12],
            ["id" => 468, "name" => "شوقان", "province_id" => 12],
            ["id" => 469, "name" => "شيروان", "province_id" => 12],
            ["id" => 470, "name" => "صفي آباد", "province_id" => 12],
            ["id" => 471, "name" => "فاروج", "province_id" => 12],
            ["id" => 472, "name" => "قاضي", "province_id" => 12],
            ["id" => 473, "name" => "گرمه", "province_id" => 12],
            ["id" => 474, "name" => "لوجلی", "province_id" => 12],
            ["id" => 475, "name" => "اروندكنار", "province_id" => 13],
            ["id" => 476, "name" => "الوان", "province_id" => 13],
            ["id" => 477, "name" => "اميديه", "province_id" => 13],
            ["id" => 478, "name" => "انديمشک", "province_id" => 13],
            ["id" => 479, "name" => "اهواز", "province_id" => 13],
            ["id" => 480, "name" => "ايذه", "province_id" => 13],
            ["id" => 481, "name" => "آبادان", "province_id" => 13],
            ["id" => 482, "name" => "آغاجاري", "province_id" => 13],
            ["id" => 483, "name" => "باغ ملک", "province_id" => 13],
            ["id" => 484, "name" => "بستان", "province_id" => 13],
            ["id" => 485, "name" => "بندرامام خميني", "province_id" => 13],
            ["id" => 486, "name" => "بندرماهشهر", "province_id" => 13],
            ["id" => 487, "name" => "بهبهان", "province_id" => 13],
            ["id" => 488, "name" => "تركالكي", "province_id" => 13],
            ["id" => 489, "name" => "جايزان", "province_id" => 13],
            ["id" => 490, "name" => "جنت مكان", "province_id" => 13],
            ["id" => 491, "name" => "چغاميش", "province_id" => 13],
            ["id" => 492, "name" => "چمران", "province_id" => 13],
            ["id" => 493, "name" => "چوئبده", "province_id" => 13],
            ["id" => 494, "name" => "حر", "province_id" => 13],
            ["id" => 495, "name" => "حسينيه", "province_id" => 13],
            ["id" => 496, "name" => "حمزه", "province_id" => 13],
            ["id" => 497, "name" => "حميديه", "province_id" => 13],
            ["id" => 498, "name" => "خرمشهر", "province_id" => 13],
            ["id" => 499, "name" => "دارخوين", "province_id" => 13],
            ["id" => 500, "name" => "دزآب", "province_id" => 13],
            ["id" => 501, "name" => "دزفول", "province_id" => 13],
            ["id" => 502, "name" => "دهدز", "province_id" => 13],
            ["id" => 503, "name" => "رامشير", "province_id" => 13],
            ["id" => 504, "name" => "رامهرمز", "province_id" => 13],
            ["id" => 505, "name" => "رفيع", "province_id" => 13],
            ["id" => 506, "name" => "زهره", "province_id" => 13],
            ["id" => 507, "name" => "سالند", "province_id" => 13],
            ["id" => 508, "name" => "سردشت", "province_id" => 13],
            ["id" => 509, "name" => "سماله", "province_id" => 13],
            ["id" => 510, "name" => "سوسنگرد", "province_id" => 13],
            ["id" => 511, "name" => "شادگان", "province_id" => 13],
            ["id" => 512, "name" => "شاوور", "province_id" => 13],
            ["id" => 513, "name" => "شرافت", "province_id" => 13],
            ["id" => 514, "name" => "شوش", "province_id" => 13],
            ["id" => 515, "name" => "شوشتر", "province_id" => 13],
            ["id" => 516, "name" => "شيبان", "province_id" => 13],
            ["id" => 517, "name" => "صالح شهر", "province_id" => 13],
            ["id" => 518, "name" => "صالح مشطط", "province_id" => 13],
            ["id" => 519, "name" => "صفي آباد", "province_id" => 13],
            ["id" => 520, "name" => "صيدون", "province_id" => 13],
            ["id" => 521, "name" => "قلعه تل", "province_id" => 13],
            ["id" => 522, "name" => "قلعه خواجه", "province_id" => 13],
            ["id" => 523, "name" => "گتوند", "province_id" => 13],
            ["id" => 524, "name" => "گوريه", "province_id" => 13],
            ["id" => 525, "name" => "لالي", "province_id" => 13],
            ["id" => 526, "name" => "مسجدسليمان", "province_id" => 13],
            ["id" => 527, "name" => "مشراگه", "province_id" => 13],
            ["id" => 528, "name" => "مقاومت", "province_id" => 13],
            ["id" => 529, "name" => "ملاثاني", "province_id" => 13],
            ["id" => 530, "name" => "ميانرود", "province_id" => 13],
            ["id" => 531, "name" => "ميداود", "province_id" => 13],
            ["id" => 532, "name" => "مينوشهر", "province_id" => 13],
            ["id" => 533, "name" => "ويس", "province_id" => 13],
            ["id" => 534, "name" => "هفتگل", "province_id" => 13],
            ["id" => 535, "name" => "هنديجان", "province_id" => 13],
            ["id" => 536, "name" => "هويزه", "province_id" => 13],
            ["id" => 537, "name" => "ابهر", "province_id" => 14],
            ["id" => 538, "name" => "ارمغانخانه", "province_id" => 14],
            ["id" => 539, "name" => "آب بر", "province_id" => 14],
            ["id" => 540, "name" => "چورزق", "province_id" => 14],
            ["id" => 541, "name" => "حلب", "province_id" => 14],
            ["id" => 542, "name" => "خرمدره", "province_id" => 14],
            ["id" => 543, "name" => "دندي", "province_id" => 14],
            ["id" => 544, "name" => "زرين آباد", "province_id" => 14],
            ["id" => 545, "name" => "زرين رود", "province_id" => 14],
            ["id" => 546, "name" => "زنجان", "province_id" => 14],
            ["id" => 547, "name" => "سجاس", "province_id" => 14],
            ["id" => 548, "name" => "سلطانيه", "province_id" => 14],
            ["id" => 549, "name" => "سهرورد", "province_id" => 14],
            ["id" => 550, "name" => "صائين قلعه", "province_id" => 14],
            ["id" => 551, "name" => "قيدار", "province_id" => 14],
            ["id" => 552, "name" => "گرماب", "province_id" => 14],
            ["id" => 553, "name" => "ماه نشان", "province_id" => 14],
            ["id" => 554, "name" => "هيدج", "province_id" => 14],
            ["id" => 555, "name" => "اميريه", "province_id" => 15],
            ["id" => 556, "name" => "ايوانكي", "province_id" => 15],
            ["id" => 557, "name" => "آرادان", "province_id" => 15],
            ["id" => 558, "name" => "بسطام", "province_id" => 15],
            ["id" => 559, "name" => "بيارجمند", "province_id" => 15],
            ["id" => 560, "name" => "دامغان", "province_id" => 15],
            ["id" => 561, "name" => "درجزين", "province_id" => 15],
            ["id" => 562, "name" => "ديباج", "province_id" => 15],
            ["id" => 563, "name" => "سرخه", "province_id" => 15],
            ["id" => 564, "name" => "سمنان", "province_id" => 15],
            ["id" => 565, "name" => "شاهرود", "province_id" => 15],
            ["id" => 566, "name" => "شهميرزاد", "province_id" => 15],
            ["id" => 567, "name" => "كلاته خيج", "province_id" => 15],
            ["id" => 568, "name" => "گرمسار", "province_id" => 15],
            ["id" => 569, "name" => "مجن", "province_id" => 15],
            ["id" => 570, "name" => "مهدي شهر", "province_id" => 15],
            ["id" => 571, "name" => "ميامی", "province_id" => 15],
            ["id" => 572, "name" => "اديمي", "province_id" => 16],
            ["id" => 573, "name" => "اسپكه", "province_id" => 16],
            ["id" => 574, "name" => "ايرانشهر", "province_id" => 16],
            ["id" => 575, "name" => "بزمان", "province_id" => 16],
            ["id" => 576, "name" => "بمپور", "province_id" => 16],
            ["id" => 577, "name" => "بنت", "province_id" => 16],
            ["id" => 578, "name" => "بنجار", "province_id" => 16],
            ["id" => 579, "name" => "پيشين", "province_id" => 16],
            ["id" => 580, "name" => "جالق", "province_id" => 16],
            ["id" => 581, "name" => "چاه بهار", "province_id" => 16],
            ["id" => 582, "name" => "خاش", "province_id" => 16],
            ["id" => 583, "name" => "دوست محمد", "province_id" => 16],
            ["id" => 584, "name" => "راسک", "province_id" => 16],
            ["id" => 585, "name" => "زابل", "province_id" => 16],
            ["id" => 586, "name" => "زابلي", "province_id" => 16],
            ["id" => 587, "name" => "زاهدان", "province_id" => 16],
            ["id" => 588, "name" => "زرآباد", "province_id" => 16],
            ["id" => 589, "name" => "زهک", "province_id" => 16],
            ["id" => 590, "name" => "سراوان", "province_id" => 16],
            ["id" => 591, "name" => "سرباز", "province_id" => 16],
            ["id" => 592, "name" => "سوران", "province_id" => 16],
            ["id" => 593, "name" => "سيركان", "province_id" => 16],
            ["id" => 594, "name" => "علي اكبر", "province_id" => 16],
            ["id" => 595, "name" => "فنوج", "province_id" => 16],
            ["id" => 596, "name" => "قصرقند", "province_id" => 16],
            ["id" => 597, "name" => "كنارک", "province_id" => 16],
            ["id" => 598, "name" => "گشت", "province_id" => 16],
            ["id" => 599, "name" => "گلمورتي", "province_id" => 16],
            ["id" => 600, "name" => "محمدان", "province_id" => 16],
            ["id" => 601, "name" => "محمد آباد", "province_id" => 16],
            ["id" => 602, "name" => "محمدي", "province_id" => 16],
            ["id" => 603, "name" => "ميرجاوه", "province_id" => 16],
            ["id" => 604, "name" => "نصرت آباد", "province_id" => 16],
            ["id" => 605, "name" => "نگور", "province_id" => 16],
            ["id" => 606, "name" => "نوک آباد", "province_id" => 16],
            ["id" => 607, "name" => "نيک شهر", "province_id" => 16],
            ["id" => 608, "name" => "هيدوج", "province_id" => 16],
            ["id" => 609, "name" => "اردكان", "province_id" => 17],
            ["id" => 610, "name" => "ارسنجان", "province_id" => 17],
            ["id" => 611, "name" => "استهبان", "province_id" => 17],
            ["id" => 612, "name" => "اسير", "province_id" => 17],
            ["id" => 613, "name" => "اشكنان", "province_id" => 17],
            ["id" => 614, "name" => "افزر", "province_id" => 17],
            ["id" => 615, "name" => "اقليد", "province_id" => 17],
            ["id" => 616, "name" => "امام شهر", "province_id" => 17],
            ["id" => 617, "name" => "اوز", "province_id" => 17],
            ["id" => 618, "name" => "اهل", "province_id" => 17],
            ["id" => 619, "name" => "ايج", "province_id" => 17],
            ["id" => 620, "name" => "ايزدخواست", "province_id" => 17],
            ["id" => 621, "name" => "آباده", "province_id" => 17],
            ["id" => 622, "name" => "آباده طشک", "province_id" => 17],
            ["id" => 623, "name" => "باب انار", "province_id" => 17],
            ["id" => 624, "name" => "بالاده", "province_id" => 17],
            ["id" => 625, "name" => "بنارويه", "province_id" => 17],
            ["id" => 626, "name" => "بوانات", "province_id" => 17],
            ["id" => 627, "name" => "بهمن", "province_id" => 17],
            ["id" => 628, "name" => "بيرم", "province_id" => 17],
            ["id" => 629, "name" => "بيضا", "province_id" => 17],
            ["id" => 630, "name" => "جنت شهر", "province_id" => 17],
            ["id" => 631, "name" => "جويم", "province_id" => 17],
            ["id" => 632, "name" => "جهرم", "province_id" => 17],
            ["id" => 633, "name" => "حاجي آباد", "province_id" => 17],
            ["id" => 634, "name" => "حسامي", "province_id" => 17],
            ["id" => 635, "name" => "حسن آباد", "province_id" => 17],
            ["id" => 636, "name" => "خانه زنيان", "province_id" => 17],
            ["id" => 637, "name" => "خاوران", "province_id" => 17],
            ["id" => 638, "name" => "خرامه", "province_id" => 17],
            ["id" => 639, "name" => "خشت", "province_id" => 17],
            ["id" => 640, "name" => "خنج", "province_id" => 17],
            ["id" => 641, "name" => "خور", "province_id" => 17],
            ["id" => 642, "name" => "خومه زار", "province_id" => 17],
            ["id" => 643, "name" => "داراب", "province_id" => 17],
            ["id" => 644, "name" => "داريان", "province_id" => 17],
            ["id" => 645, "name" => "دبيران", "province_id" => 17],
            ["id" => 646, "name" => "دژكرد", "province_id" => 17],
            ["id" => 647, "name" => "دوبرجي", "province_id" => 17],
            ["id" => 648, "name" => "دوزه", "province_id" => 17],
            ["id" => 649, "name" => "دهرم", "province_id" => 17],
            ["id" => 650, "name" => "رامجرد", "province_id" => 17],
            ["id" => 651, "name" => "رونيز", "province_id" => 17],
            ["id" => 652, "name" => "زاهدشهر", "province_id" => 17],
            ["id" => 653, "name" => "زرقان", "province_id" => 17],
            ["id" => 654, "name" => "سده", "province_id" => 17],
            ["id" => 655, "name" => "سروستان", "province_id" => 17],
            ["id" => 656, "name" => "سعادت شهر", "province_id" => 17],
            ["id" => 657, "name" => "سورمق", "province_id" => 17],
            ["id" => 658, "name" => "سيدان", "province_id" => 17],
            ["id" => 659, "name" => "ششده", "province_id" => 17],
            ["id" => 660, "name" => "شهر جديد صدرا", "province_id" => 17],
            ["id" => 661, "name" => "شهرپير", "province_id" => 17],
            ["id" => 662, "name" => "شيراز", "province_id" => 17],
            ["id" => 663, "name" => "صغاد", "province_id" => 17],
            ["id" => 664, "name" => "صفاشهر", "province_id" => 17],
            ["id" => 665, "name" => "علامرودشت", "province_id" => 17],
            ["id" => 666, "name" => "عمادده", "province_id" => 17],
            ["id" => 667, "name" => "فدامي", "province_id" => 17],
            ["id" => 668, "name" => "فراشبند", "province_id" => 17],
            ["id" => 669, "name" => "فسا", "province_id" => 17],
            ["id" => 670, "name" => "فيروزآباد", "province_id" => 17],
            ["id" => 671, "name" => "قادرآباد", "province_id" => 17],
            ["id" => 672, "name" => "قائميه", "province_id" => 17],
            ["id" => 673, "name" => "قطب آباد", "province_id" => 17],
            ["id" => 674, "name" => "قطرويه", "province_id" => 17],
            ["id" => 675, "name" => "قير", "province_id" => 17],
            ["id" => 676, "name" => "كارزين", "province_id" => 17],
            ["id" => 677, "name" => "كازرون", "province_id" => 17],
            ["id" => 678, "name" => "كامفيروز", "province_id" => 17],
            ["id" => 679, "name" => "كره اي", "province_id" => 17],
            ["id" => 680, "name" => "كنارتخته", "province_id" => 17],
            ["id" => 681, "name" => "كوار", "province_id" => 17],
            ["id" => 682, "name" => "كوهنجان", "province_id" => 17],
            ["id" => 683, "name" => "گراش", "province_id" => 17],
            ["id" => 684, "name" => "گله دار", "province_id" => 17],
            ["id" => 685, "name" => "لار", "province_id" => 17],
            ["id" => 686, "name" => "لامرد", "province_id" => 17],
            ["id" => 687, "name" => "لپوئي", "province_id" => 17],
            ["id" => 688, "name" => "لطيفي", "province_id" => 17],
            ["id" => 689, "name" => "مبارك آباد", "province_id" => 17],
            ["id" => 690, "name" => "مرودشت", "province_id" => 17],
            ["id" => 691, "name" => "مشكان", "province_id" => 17],
            ["id" => 692, "name" => "مصيري", "province_id" => 17],
            ["id" => 693, "name" => "مهر", "province_id" => 17],
            ["id" => 694, "name" => "ميمند", "province_id" => 17],
            ["id" => 695, "name" => "نوبندگان", "province_id" => 17],
            ["id" => 696, "name" => "نوجين", "province_id" => 17],
            ["id" => 697, "name" => "نودان", "province_id" => 17],
            ["id" => 698, "name" => "نورآباد", "province_id" => 17],
            ["id" => 699, "name" => "ني ريز", "province_id" => 17],
            ["id" => 700, "name" => "وراوي", "province_id" => 17],
            ["id" => 701, "name" => "هماشهر", "province_id" => 17],
            ["id" => 702, "name" => "ارداق", "province_id" => 18],
            ["id" => 703, "name" => "اسفرورين", "province_id" => 18],
            ["id" => 704, "name" => "اقباليه", "province_id" => 18],
            ["id" => 705, "name" => "الوند", "province_id" => 18],
            ["id" => 706, "name" => "آبگرم", "province_id" => 18],
            ["id" => 707, "name" => "آبيک", "province_id" => 18],
            ["id" => 708, "name" => "آوج", "province_id" => 18],
            ["id" => 709, "name" => "بوئين زهرا", "province_id" => 18],
            ["id" => 710, "name" => "بيدستان", "province_id" => 18],
            ["id" => 711, "name" => "تاكستان", "province_id" => 18],
            ["id" => 712, "name" => "خاكعلي", "province_id" => 18],
            ["id" => 713, "name" => "خرمدشت", "province_id" => 18],
            ["id" => 714, "name" => "دانسفهان", "province_id" => 18],
            ["id" => 715, "name" => "رازميان", "province_id" => 18],
            ["id" => 716, "name" => "سگزآباد", "province_id" => 18],
            ["id" => 717, "name" => "سيردان", "province_id" => 18],
            ["id" => 718, "name" => "شال", "province_id" => 18],
            ["id" => 719, "name" => "شريفيه", "province_id" => 18],
            ["id" => 720, "name" => "ضياءآباد", "province_id" => 18],
            ["id" => 721, "name" => "قزوين", "province_id" => 18],
            ["id" => 722, "name" => "كوهين", "province_id" => 18],
            ["id" => 723, "name" => "محمديه", "province_id" => 18],
            ["id" => 724, "name" => "محمودآبادنمونه", "province_id" => 18],
            ["id" => 725, "name" => "معلم كلايه", "province_id" => 18],
            ["id" => 726, "name" => "نرجه", "province_id" => 18],
            ["id" => 727, "name" => "جعفريه", "province_id" => 19],
            ["id" => 728, "name" => "دستجرد", "province_id" => 19],
            ["id" => 729, "name" => "سلفچگان", "province_id" => 19],
            ["id" => 730, "name" => "قم", "province_id" => 19],
            ["id" => 731, "name" => "قنوات", "province_id" => 19],
            ["id" => 732, "name" => "كهک", "province_id" => 19],
            ["id" => 733, "name" => "آرمرده", "province_id" => 20],
            ["id" => 734, "name" => "بابارشاني", "province_id" => 20],
            ["id" => 735, "name" => "بانه", "province_id" => 20],
            ["id" => 736, "name" => "بلبان آباد", "province_id" => 20],
            ["id" => 737, "name" => "بوئين سفلي", "province_id" => 20],
            ["id" => 738, "name" => "بيجار", "province_id" => 20],
            ["id" => 739, "name" => "چناره", "province_id" => 20],
            ["id" => 740, "name" => "دزج", "province_id" => 20],
            ["id" => 741, "name" => "دلبران", "province_id" => 20],
            ["id" => 742, "name" => "دهگلان", "province_id" => 20],
            ["id" => 743, "name" => "ديواندره", "province_id" => 20],
            ["id" => 744, "name" => "زرينه", "province_id" => 20],
            ["id" => 745, "name" => "سروآباد", "province_id" => 20],
            ["id" => 746, "name" => "سريش آباد", "province_id" => 20],
            ["id" => 747, "name" => "سقز", "province_id" => 20],
            ["id" => 748, "name" => "سنندج", "province_id" => 20],
            ["id" => 749, "name" => "شويشه", "province_id" => 20],
            ["id" => 750, "name" => "صاحب", "province_id" => 20],
            ["id" => 751, "name" => "قروه", "province_id" => 20],
            ["id" => 752, "name" => "كامياران", "province_id" => 20],
            ["id" => 753, "name" => "كاني دينار", "province_id" => 20],
            ["id" => 754, "name" => "كاني سور", "province_id" => 20],
            ["id" => 755, "name" => "مريوان", "province_id" => 20],
            ["id" => 756, "name" => "موچش", "province_id" => 20],
            ["id" => 757, "name" => "ياسوكند", "province_id" => 20],
            ["id" => 758, "name" => "اختيارآباد", "province_id" => 21],
            ["id" => 759, "name" => "ارزوئيه", "province_id" => 21],
            ["id" => 760, "name" => "امين شهر", "province_id" => 21],
            ["id" => 761, "name" => "انار", "province_id" => 21],
            ["id" => 762, "name" => "اندوهجرد", "province_id" => 21],
            ["id" => 763, "name" => "باغين", "province_id" => 21],
            ["id" => 764, "name" => "بافت", "province_id" => 21],
            ["id" => 765, "name" => "بردسير", "province_id" => 21],
            ["id" => 766, "name" => "بروات", "province_id" => 21],
            ["id" => 767, "name" => "بزنجان", "province_id" => 21],
            ["id" => 768, "name" => "بم", "province_id" => 21],
            ["id" => 769, "name" => "بهرمان", "province_id" => 21],
            ["id" => 770, "name" => "پاريز", "province_id" => 21],
            ["id" => 771, "name" => "جبالبارز", "province_id" => 21],
            ["id" => 772, "name" => "جوپار", "province_id" => 21],
            ["id" => 773, "name" => "جوزم", "province_id" => 21],
            ["id" => 774, "name" => "جيرفت", "province_id" => 21],
            ["id" => 775, "name" => "چترود", "province_id" => 21],
            ["id" => 776, "name" => "خاتون آباد", "province_id" => 21],
            ["id" => 777, "name" => "خانوک", "province_id" => 21],
            ["id" => 778, "name" => "خورسند", "province_id" => 21],
            ["id" => 779, "name" => "درب بهشت", "province_id" => 21],
            ["id" => 780, "name" => "دوساري", "province_id" => 21],
            ["id" => 781, "name" => "دهج", "province_id" => 21],
            ["id" => 782, "name" => "رابر", "province_id" => 21],
            ["id" => 783, "name" => "راور", "province_id" => 21],
            ["id" => 784, "name" => "راين", "province_id" => 21],
            ["id" => 785, "name" => "رفسنجان", "province_id" => 21],
            ["id" => 786, "name" => "رودبار", "province_id" => 21],
            ["id" => 787, "name" => "ريحان شهر", "province_id" => 21],
            ["id" => 788, "name" => "زرند", "province_id" => 21],
            ["id" => 789, "name" => "زنگي آباد", "province_id" => 21],
            ["id" => 790, "name" => "زيدآباد", "province_id" => 21],
            ["id" => 791, "name" => "سرچشمه", "province_id" => 21],
            ["id" => 792, "name" => "سيرجان", "province_id" => 21],
            ["id" => 793, "name" => "شهداد", "province_id" => 21],
            ["id" => 794, "name" => "شهربابك", "province_id" => 21],
            ["id" => 795, "name" => "صفائيه", "province_id" => 21],
            ["id" => 796, "name" => "عنبرآباد", "province_id" => 21],
            ["id" => 797, "name" => "فارياب", "province_id" => 21],
            ["id" => 798, "name" => "فهرج", "province_id" => 21],
            ["id" => 799, "name" => "قلعه گنج", "province_id" => 21],
            ["id" => 800, "name" => "كاظم آباد", "province_id" => 21],
            ["id" => 801, "name" => "كرمان", "province_id" => 21],
            ["id" => 802, "name" => "كشكوئيه", "province_id" => 21],
            ["id" => 803, "name" => "كوهبنان", "province_id" => 21],
            ["id" => 804, "name" => "كهنوج", "province_id" => 21],
            ["id" => 805, "name" => "كيانشهر", "province_id" => 21],
            ["id" => 806, "name" => "گلباف", "province_id" => 21],
            ["id" => 807, "name" => "گلزار", "province_id" => 21],
            ["id" => 808, "name" => "لاله زار", "province_id" => 21],
            ["id" => 809, "name" => "ماهان", "province_id" => 21],
            ["id" => 810, "name" => "محمد آباد", "province_id" => 21],
            ["id" => 811, "name" => "محي آباد", "province_id" => 21],
            ["id" => 812, "name" => "مردهک", "province_id" => 21],
            ["id" => 813, "name" => "منوجان", "province_id" => 21],
            ["id" => 814, "name" => "نجف شهر", "province_id" => 21],
            ["id" => 815, "name" => "نرماشير", "province_id" => 21],
            ["id" => 816, "name" => "نظام شهر", "province_id" => 21],
            ["id" => 817, "name" => "نگار", "province_id" => 21],
            ["id" => 818, "name" => "نودژ", "province_id" => 21],
            ["id" => 819, "name" => "هجدک", "province_id" => 21],
            ["id" => 820, "name" => "هماشهر", "province_id" => 21],
            ["id" => 821, "name" => "يزدان شهر", "province_id" => 21],
            ["id" => 822, "name" => "ازگله", "province_id" => 22],
            ["id" => 823, "name" => "اسلام آبادغرب", "province_id" => 22],
            ["id" => 824, "name" => "باينگان", "province_id" => 22],
            ["id" => 825, "name" => "بيستون", "province_id" => 22],
            ["id" => 826, "name" => "پاوه", "province_id" => 22],
            ["id" => 827, "name" => "تازه آباد", "province_id" => 22],
            ["id" => 828, "name" => "جوانرود", "province_id" => 22],
            ["id" => 829, "name" => "حميل", "province_id" => 22],
            ["id" => 830, "name" => "رباط", "province_id" => 22],
            ["id" => 831, "name" => "روانسر", "province_id" => 22],
            ["id" => 832, "name" => "سرپل ذهاب", "province_id" => 22],
            ["id" => 833, "name" => "سرمست", "province_id" => 22],
            ["id" => 834, "name" => "سطر", "province_id" => 22],
            ["id" => 835, "name" => "سنقر", "province_id" => 22],
            ["id" => 836, "name" => "سومار", "province_id" => 22],
            ["id" => 837, "name" => "شاهو", "province_id" => 22],
            ["id" => 838, "name" => "صحنه", "province_id" => 22],
            ["id" => 839, "name" => "قصرشيرين", "province_id" => 22],
            ["id" => 840, "name" => "كرمانشاه", "province_id" => 22],
            ["id" => 841, "name" => "كرندغرب", "province_id" => 22],
            ["id" => 842, "name" => "كنگاور", "province_id" => 22],
            ["id" => 843, "name" => "كوزران", "province_id" => 22],
            ["id" => 844, "name" => "گهواره", "province_id" => 22],
            ["id" => 845, "name" => "گيلانغرب", "province_id" => 22],
            ["id" => 846, "name" => "ميان راهان", "province_id" => 22],
            ["id" => 847, "name" => "نودشه", "province_id" => 22],
            ["id" => 848, "name" => "نوسود", "province_id" => 22],
            ["id" => 849, "name" => "هرسين", "province_id" => 22],
            ["id" => 850, "name" => "هلشي", "province_id" => 22],
            ["id" => 851, "name" => "باشت", "province_id" => 23],
            ["id" => 852, "name" => "پاتاوه", "province_id" => 23],
            ["id" => 853, "name" => "چرام", "province_id" => 23],
            ["id" => 854, "name" => "چيتاب", "province_id" => 23],
            ["id" => 855, "name" => "دوگنبدان", "province_id" => 23],
            ["id" => 856, "name" => "دهدشت", "province_id" => 23],
            ["id" => 857, "name" => "ديشموک", "province_id" => 23],
            ["id" => 858, "name" => "سوق", "province_id" => 23],
            ["id" => 859, "name" => "سي سخت", "province_id" => 23],
            ["id" => 860, "name" => "قلعه رئيسي", "province_id" => 23],
            ["id" => 861, "name" => "گراب سفلي", "province_id" => 23],
            ["id" => 862, "name" => "لنده", "province_id" => 23],
            ["id" => 863, "name" => "ليكک", "province_id" => 23],
            ["id" => 864, "name" => "مادوان", "province_id" => 23],
            ["id" => 865, "name" => "مارگون", "province_id" => 23],
            ["id" => 866, "name" => "ياسوج", "province_id" => 23],
            ["id" => 867, "name" => "انبارآلوم", "province_id" => 24],
            ["id" => 868, "name" => "اينچه برون", "province_id" => 24],
            ["id" => 869, "name" => "آزادشهر", "province_id" => 24],
            ["id" => 870, "name" => "آق قلا", "province_id" => 24],
            ["id" => 871, "name" => "بندرگز", "province_id" => 24],
            ["id" => 872, "name" => "تركمن", "province_id" => 24],
            ["id" => 873, "name" => "جلين", "province_id" => 24],
            ["id" => 874, "name" => "خان ببين", "province_id" => 24],
            ["id" => 875, "name" => "دلند", "province_id" => 24],
            ["id" => 876, "name" => "راميان", "province_id" => 24],
            ["id" => 877, "name" => "سرخنكلاته", "province_id" => 24],
            ["id" => 878, "name" => "سيمين شهر", "province_id" => 24],
            ["id" => 879, "name" => "علي آباد", "province_id" => 24],
            ["id" => 880, "name" => "فاضل آباد", "province_id" => 24],
            ["id" => 881, "name" => "كردكوي", "province_id" => 24],
            ["id" => 882, "name" => "كلاله", "province_id" => 24],
            ["id" => 883, "name" => "گاليكش", "province_id" => 24],
            ["id" => 884, "name" => "گرگان", "province_id" => 24],
            ["id" => 885, "name" => "گميش تپه", "province_id" => 24],
            ["id" => 886, "name" => "گنبد كاووس", "province_id" => 24],
            ["id" => 887, "name" => "مراوه تپه", "province_id" => 24],
            ["id" => 888, "name" => "مينودشت", "province_id" => 24],
            ["id" => 889, "name" => "نگين شهر", "province_id" => 24],
            ["id" => 890, "name" => "نوده خاندوز", "province_id" => 24],
            ["id" => 891, "name" => "نوكنده", "province_id" => 24],
            ["id" => 892, "name" => "احمدسرگوراب", "province_id" => 1],
            ["id" => 893, "name" => "اسالم", "province_id" => 1],
            ["id" => 894, "name" => "اطاقور", "province_id" => 1],
            ["id" => 895, "name" => "املش", "province_id" => 1],
            ["id" => 896, "name" => "آستارا", "province_id" => 1],
            ["id" => 897, "name" => "آستانه اشرفيه", "province_id" => 1],
            ["id" => 898, "name" => "بازارجمعه", "province_id" => 1],
            ["id" => 899, "name" => "بره سر", "province_id" => 1],
            ["id" => 900, "name" => "بندرانزلي", "province_id" => 1],
            ["id" => 901, "name" => "پره سر", "province_id" => 1],
            ["id" => 902, "name" => "تونكابن", "province_id" => 1],
            ["id" => 903, "name" => "جيرنده", "province_id" => 1],
            ["id" => 904, "name" => "چابكسر", "province_id" => 1],
            ["id" => 905, "name" => "چاف وچمخاله", "province_id" => 1],
            ["id" => 906, "name" => "چوبر", "province_id" => 1],
            ["id" => 907, "name" => "حويق", "province_id" => 1],
            ["id" => 908, "name" => "خشكبيجار", "province_id" => 1],
            ["id" => 909, "name" => "خمام", "province_id" => 1],
            ["id" => 910, "name" => "ديلمان", "province_id" => 1],
            ["id" => 911, "name" => "رانكوه", "province_id" => 1],
            ["id" => 912, "name" => "رحيم آباد", "province_id" => 1],
            ["id" => 913, "name" => "رستم آباد", "province_id" => 1],
            ["id" => 914, "name" => "رشت", "province_id" => 1],
            ["id" => 915, "name" => "رضوانشهر", "province_id" => 1],
            ["id" => 916, "name" => "رودبار", "province_id" => 1],
            ["id" => 917, "name" => "رودبنه", "province_id" => 1],
            ["id" => 918, "name" => "رودسر", "province_id" => 1],
            ["id" => 919, "name" => "سنگر", "province_id" => 1],
            ["id" => 920, "name" => "سياهكل", "province_id" => 1],
            ["id" => 921, "name" => "شفت", "province_id" => 1],
            ["id" => 922, "name" => "شلمان", "province_id" => 1],
            ["id" => 923, "name" => "صومعه سرا", "province_id" => 1],
            ["id" => 924, "name" => "فومن", "province_id" => 1],
            ["id" => 925, "name" => "كلاچاي", "province_id" => 1],
            ["id" => 926, "name" => "كوچصفهان", "province_id" => 1],
            ["id" => 927, "name" => "كومله", "province_id" => 1],
            ["id" => 928, "name" => "كياشهر", "province_id" => 1],
            ["id" => 929, "name" => "گوراب زرميخ", "province_id" => 1],
            ["id" => 930, "name" => "لاهيجان", "province_id" => 1],
            ["id" => 931, "name" => "لشت نشاء", "province_id" => 1],
            ["id" => 932, "name" => "لنگرود", "province_id" => 1],
            ["id" => 933, "name" => "لوشان", "province_id" => 1],
            ["id" => 934, "name" => "لولمان", "province_id" => 1],
            ["id" => 935, "name" => "لوندويل", "province_id" => 1],
            ["id" => 936, "name" => "ليسار", "province_id" => 1],
            ["id" => 937, "name" => "ماسال", "province_id" => 1],
            ["id" => 938, "name" => "ماسوله", "province_id" => 1],
            ["id" => 939, "name" => "مرجقل", "province_id" => 1],
            ["id" => 940, "name" => "منجيل", "province_id" => 1],
            ["id" => 941, "name" => "واجارگاه", "province_id" => 1],
            ["id" => 942, "name" => "هشتپر", "province_id" => 1],
            ["id" => 943, "name" => "ازنا", "province_id" => 26],
            ["id" => 944, "name" => "اشترينان", "province_id" => 26],
            ["id" => 945, "name" => "الشتر", "province_id" => 26],
            ["id" => 946, "name" => "اليگودرز", "province_id" => 26],
            ["id" => 947, "name" => "بروجرد", "province_id" => 26],
            ["id" => 948, "name" => "پلدختر", "province_id" => 26],
            ["id" => 949, "name" => "چالانچولان", "province_id" => 26],
            ["id" => 950, "name" => "چغلوندي", "province_id" => 26],
            ["id" => 951, "name" => "چقابل", "province_id" => 26],
            ["id" => 952, "name" => "خرم آباد", "province_id" => 26],
            ["id" => 953, "name" => "درب گنبد", "province_id" => 26],
            ["id" => 954, "name" => "دورود", "province_id" => 26],
            ["id" => 955, "name" => "زاغه", "province_id" => 26],
            ["id" => 956, "name" => "سپيددشت", "province_id" => 26],
            ["id" => 957, "name" => "سراب دوره", "province_id" => 26],
            ["id" => 958, "name" => "شول آباد", "province_id" => 26],
            ["id" => 959, "name" => "فيروز آباد", "province_id" => 26],
            ["id" => 960, "name" => "كوناني", "province_id" => 26],
            ["id" => 961, "name" => "كوهدشت", "province_id" => 26],
            ["id" => 962, "name" => "گراب", "province_id" => 26],
            ["id" => 963, "name" => "معمولان", "province_id" => 26],
            ["id" => 964, "name" => "مؤمن آباد", "province_id" => 26],
            ["id" => 965, "name" => "نور آباد", "province_id" => 26],
            ["id" => 966, "name" => "ويسيان", "province_id" => 26],
            ["id" => 967, "name" => "هفت چشمه", "province_id" => 26],
            ["id" => 968, "name" => "اميركلا", "province_id" => 27],
            ["id" => 969, "name" => "ايزدشهر", "province_id" => 27],
            ["id" => 970, "name" => "آلاشت", "province_id" => 27],
            ["id" => 971, "name" => "آمل", "province_id" => 27],
            ["id" => 972, "name" => "بابل", "province_id" => 27],
            ["id" => 973, "name" => "بابلسر", "province_id" => 27],
            ["id" => 974, "name" => "بلده", "province_id" => 27],
            ["id" => 975, "name" => "بهشهر", "province_id" => 27],
            ["id" => 976, "name" => "بهنمير", "province_id" => 27],
            ["id" => 977, "name" => "پل سفيد", "province_id" => 27],
            ["id" => 978, "name" => "پول", "province_id" => 27],
            ["id" => 979, "name" => "تنكابن", "province_id" => 27],
            ["id" => 980, "name" => "جويبار", "province_id" => 27],
            ["id" => 981, "name" => "چالوس", "province_id" => 27],
            ["id" => 982, "name" => "چمستان", "province_id" => 27],
            ["id" => 983, "name" => "خرم آباد", "province_id" => 27],
            ["id" => 984, "name" => "خليل شهر", "province_id" => 27],
            ["id" => 985, "name" => "خوش رودپي", "province_id" => 27],
            ["id" => 986, "name" => "دابودشت", "province_id" => 27],
            ["id" => 987, "name" => "رامسر", "province_id" => 27],
            ["id" => 988, "name" => "رستمكلا", "province_id" => 27],
            ["id" => 989, "name" => "رويان", "province_id" => 27],
            ["id" => 990, "name" => "رينه", "province_id" => 27],
            ["id" => 991, "name" => "زرگر محله", "province_id" => 27],
            ["id" => 992, "name" => "زيرآب", "province_id" => 27],
            ["id" => 993, "name" => "ساري", "province_id" => 27],
            ["id" => 994, "name" => "سرخرود", "province_id" => 27],
            ["id" => 995, "name" => "سلمان شهر", "province_id" => 27],
            ["id" => 996, "name" => "سورک", "province_id" => 27],
            ["id" => 997, "name" => "شيرگاه", "province_id" => 27],
            ["id" => 998, "name" => "شيرود", "province_id" => 27],
            ["id" => 999, "name" => "عباس آباد", "province_id" => 27],
            ["id" => 1000, "name" => "فريدونكنار", "province_id" => 27],
            ["id" => 1001, "name" => "فريم", "province_id" => 27],
            ["id" => 1002, "name" => "قائم شهر", "province_id" => 27],
            ["id" => 1003, "name" => "كتالم وسادات شهر", "province_id" => 27],
            ["id" => 1004, "name" => "كلارآباد", "province_id" => 27],
            ["id" => 1005, "name" => "كلاردشت", "province_id" => 27],
            ["id" => 1006, "name" => "كله بست", "province_id" => 27],
            ["id" => 1007, "name" => "كوهي خيل", "province_id" => 27],
            ["id" => 1008, "name" => "كياسر", "province_id" => 27],
            ["id" => 1009, "name" => "كياكلا", "province_id" => 27],
            ["id" => 1010, "name" => "گتاب", "province_id" => 27],
            ["id" => 1011, "name" => "گزنک", "province_id" => 27],
            ["id" => 1012, "name" => "گلوگاه", "province_id" => 27],
            ["id" => 1013, "name" => "محمود آباد", "province_id" => 27],
            ["id" => 1014, "name" => "مرزن آباد", "province_id" => 27],
            ["id" => 1015, "name" => "مرزيكلا", "province_id" => 27],
            ["id" => 1016, "name" => "نشتارود", "province_id" => 27],
            ["id" => 1017, "name" => "نكا", "province_id" => 27],
            ["id" => 1018, "name" => "نور", "province_id" => 27],
            ["id" => 1019, "name" => "نوشهر", "province_id" => 27],
            ["id" => 1020, "name" => "اراک", "province_id" => 28],
            ["id" => 1021, "name" => "آستانه", "province_id" => 28],
            ["id" => 1022, "name" => "آشتيان", "province_id" => 28],
            ["id" => 1023, "name" => "پرندک", "province_id" => 28],
            ["id" => 1024, "name" => "تفرش", "province_id" => 28],
            ["id" => 1025, "name" => "توره", "province_id" => 28],
            ["id" => 1026, "name" => "جاورسيان", "province_id" => 28],
            ["id" => 1027, "name" => "خشكرود", "province_id" => 28],
            ["id" => 1028, "name" => "خمين", "province_id" => 28],
            ["id" => 1029, "name" => "خنداب", "province_id" => 28],
            ["id" => 1030, "name" => "داودآباد", "province_id" => 28],
            ["id" => 1031, "name" => "دليجان", "province_id" => 28],
            ["id" => 1032, "name" => "رازقان", "province_id" => 28],
            ["id" => 1033, "name" => "زاويه", "province_id" => 28],
            ["id" => 1034, "name" => "ساروق", "province_id" => 28],
            ["id" => 1035, "name" => "ساوه", "province_id" => 28],
            ["id" => 1036, "name" => "سنجان", "province_id" => 28],
            ["id" => 1037, "name" => "شازند", "province_id" => 28],
            ["id" => 1038, "name" => "شهرجديدمهاجران", "province_id" => 28],
            ["id" => 1039, "name" => "غرق آباد", "province_id" => 28],
            ["id" => 1040, "name" => "فرمهين", "province_id" => 28],
            ["id" => 1041, "name" => "قورچي باشي", "province_id" => 28],
            ["id" => 1042, "name" => "كرهرود", "province_id" => 28],
            ["id" => 1043, "name" => "كميجان", "province_id" => 28],
            ["id" => 1044, "name" => "مأمونيه", "province_id" => 28],
            ["id" => 1045, "name" => "محلات", "province_id" => 28],
            ["id" => 1046, "name" => "ميلاجرد", "province_id" => 28],
            ["id" => 1047, "name" => "نراق", "province_id" => 28],
            ["id" => 1048, "name" => "نوبران", "province_id" => 28],
            ["id" => 1049, "name" => "نيمور", "province_id" => 28],
            ["id" => 1050, "name" => "هندودر", "province_id" => 28],
            ["id" => 1051, "name" => "ابوموسي", "province_id" => 29],
            ["id" => 1052, "name" => "بستک", "province_id" => 29],
            ["id" => 1053, "name" => "بندرجاسک", "province_id" => 29],
            ["id" => 1054, "name" => "بندرچارک", "province_id" => 29],
            ["id" => 1055, "name" => "بندرعباس", "province_id" => 29],
            ["id" => 1056, "name" => "بندرلنگه", "province_id" => 29],
            ["id" => 1057, "name" => "بيكاه", "province_id" => 29],
            ["id" => 1058, "name" => "پارسيان", "province_id" => 29],
            ["id" => 1059, "name" => "تخت", "province_id" => 29],
            ["id" => 1060, "name" => "جناح", "province_id" => 29],
            ["id" => 1061, "name" => "حاجي آباد", "province_id" => 29],
            ["id" => 1062, "name" => "خمير", "province_id" => 29],
            ["id" => 1063, "name" => "درگهان", "province_id" => 29],
            ["id" => 1064, "name" => "دهبارز", "province_id" => 29],
            ["id" => 1065, "name" => "رويدر", "province_id" => 29],
            ["id" => 1066, "name" => "زيارتعلي", "province_id" => 29],
            ["id" => 1067, "name" => "سردشت شاگرد", "province_id" => 29],
            ["id" => 1068, "name" => "سرگز", "province_id" => 29],
            ["id" => 1069, "name" => "سندرک", "province_id" => 29],
            ["id" => 1070, "name" => "سوزا", "province_id" => 29],
            ["id" => 1071, "name" => "سيريک", "province_id" => 29],
            ["id" => 1072, "name" => "فارغان", "province_id" => 29],
            ["id" => 1073, "name" => "فين", "province_id" => 29],
            ["id" => 1074, "name" => "قشم", "province_id" => 29],
            ["id" => 1075, "name" => "قلعه قاضي", "province_id" => 29],
            ["id" => 1076, "name" => "كنگ", "province_id" => 29],
            ["id" => 1077, "name" => "كوشكنار", "province_id" => 29],
            ["id" => 1078, "name" => "كيش", "province_id" => 29],
            ["id" => 1079, "name" => "گوهران", "province_id" => 29],
            ["id" => 1080, "name" => "ميناب", "province_id" => 29],
            ["id" => 1081, "name" => "هرمز", "province_id" => 29],
            ["id" => 1082, "name" => "هشتبندي", "province_id" => 29],
            ["id" => 1083, "name" => "ازندريان", "province_id" => 30],
            ["id" => 1084, "name" => "اسدآباد", "province_id" => 30],
            ["id" => 1085, "name" => "برزول", "province_id" => 30],
            ["id" => 1086, "name" => "بهار", "province_id" => 30],
            ["id" => 1087, "name" => "تويسركان", "province_id" => 30],
            ["id" => 1088, "name" => "جورقان", "province_id" => 30],
            ["id" => 1089, "name" => "جوكار", "province_id" => 30],
            ["id" => 1090, "name" => "دمق", "province_id" => 30],
            ["id" => 1091, "name" => "رزن", "province_id" => 30],
            ["id" => 1092, "name" => "زنگنه", "province_id" => 30],
            ["id" => 1093, "name" => "سامن", "province_id" => 30],
            ["id" => 1094, "name" => "سركان", "province_id" => 30],
            ["id" => 1095, "name" => "شيرين سو", "province_id" => 30],
            ["id" => 1096, "name" => "صالح آباد", "province_id" => 30],
            ["id" => 1097, "name" => "فامنين", "province_id" => 30],
            ["id" => 1098, "name" => "فرسفج", "province_id" => 30],
            ["id" => 1099, "name" => "فيروزان", "province_id" => 30],
            ["id" => 1100, "name" => "قروه در جزين", "province_id" => 30],
            ["id" => 1101, "name" => "قهاوند", "province_id" => 30],
            ["id" => 1102, "name" => "كبودرآهنگ", "province_id" => 30],
            ["id" => 1103, "name" => "گل تپه", "province_id" => 30],
            ["id" => 1104, "name" => "گيان", "province_id" => 30],
            ["id" => 1105, "name" => "لالجين", "province_id" => 30],
            ["id" => 1106, "name" => "مريانج", "province_id" => 30],
            ["id" => 1107, "name" => "ملاير", "province_id" => 30],
            ["id" => 1108, "name" => "نهاوند", "province_id" => 30],
            ["id" => 1109, "name" => "همدان", "province_id" => 30],
            ["id" => 1110, "name" => "ابركوه", "province_id" => 31],
            ["id" => 1111, "name" => "احمدآباد", "province_id" => 31],
            ["id" => 1112, "name" => "اردكان", "province_id" => 31],
            ["id" => 1113, "name" => "اشكذر", "province_id" => 31],
            ["id" => 1114, "name" => "بافق", "province_id" => 31],
            ["id" => 1115, "name" => "بفروئيه", "province_id" => 31],
            ["id" => 1116, "name" => "بهاباد", "province_id" => 31],
            ["id" => 1117, "name" => "تفت", "province_id" => 31],
            ["id" => 1118, "name" => "حميديا", "province_id" => 31],
            ["id" => 1119, "name" => "خضرآباد", "province_id" => 31],
            ["id" => 1120, "name" => "ديهوک", "province_id" => 31],
            ["id" => 1121, "name" => "زارچ", "province_id" => 31],
            ["id" => 1122, "name" => "شاهديه", "province_id" => 31],
            ["id" => 1123, "name" => "طبس", "province_id" => 31],
            ["id" => 1124, "name" => "عشق آباد", "province_id" => 31],
            ["id" => 1125, "name" => "عقدا", "province_id" => 31],
            ["id" => 1126, "name" => "مروست", "province_id" => 31],
            ["id" => 1127, "name" => "مهردشت", "province_id" => 31],
            ["id" => 1128, "name" => "مهريز", "province_id" => 31],
            ["id" => 1129, "name" => "ميبد", "province_id" => 31],
            ["id" => 1130, "name" => "ندوشن", "province_id" => 31],
            ["id" => 1131, "name" => "نير", "province_id" => 31],
            ["id" => 1132, "name" => "هرات", "province_id" => 31],
            ["id" => 1133, "name" => "يزد", "province_id" => 31],
            ["id" => 1134, "name" => "احمدسرگوراب", "province_id" => 25],
            ["id" => 1135, "name" => "اسالم", "province_id" => 25],
            ["id" => 1136, "name" => "اطاقور", "province_id" => 25],
            ["id" => 1137, "name" => "املش", "province_id" => 25],
            ["id" => 1138, "name" => "آستارا", "province_id" => 25],
            ["id" => 1139, "name" => "آستانه اشرفيه", "province_id" => 25],
            ["id" => 1140, "name" => "بازارجمعه", "province_id" => 25],
            ["id" => 1141, "name" => "بره سر", "province_id" => 25],
            ["id" => 1142, "name" => "بندرانزلي", "province_id" => 25],
            ["id" => 1143, "name" => "پره سر", "province_id" => 25],
            ["id" => 1144, "name" => "تونكابن", "province_id" => 25],
            ["id" => 1145, "name" => "جيرنده", "province_id" => 25],
            ["id" => 1146, "name" => "چابكسر", "province_id" => 25],
            ["id" => 1147, "name" => "چاف وچمخاله", "province_id" => 25],
            ["id" => 1148, "name" => "چوبر", "province_id" => 25],
            ["id" => 1149, "name" => "حويق", "province_id" => 25],
            ["id" => 1150, "name" => "خشكبيجار", "province_id" => 25],
            ["id" => 1151, "name" => "خمام", "province_id" => 25],
            ["id" => 1152, "name" => "ديلمان", "province_id" => 25],
            ["id" => 1153, "name" => "رانكوه", "province_id" => 25],
            ["id" => 1154, "name" => "رحيم آباد", "province_id" => 25],
            ["id" => 1155, "name" => "رستم آباد", "province_id" => 25],
            ["id" => 1156, "name" => "رشت", "province_id" => 25],
            ["id" => 1157, "name" => "رضوانشهر", "province_id" => 25],
            ["id" => 1158, "name" => "رودبار", "province_id" => 25],
            ["id" => 1159, "name" => "رودبنه", "province_id" => 25],
            ["id" => 1160, "name" => "رودسر", "province_id" => 25],
            ["id" => 1161, "name" => "سنگر", "province_id" => 25],
            ["id" => 1162, "name" => "سياهكل", "province_id" => 25],
            ["id" => 1163, "name" => "شفت", "province_id" => 25],
            ["id" => 1164, "name" => "شلمان", "province_id" => 25],
            ["id" => 1165, "name" => "صومعه سرا", "province_id" => 25],
            ["id" => 1166, "name" => "فومن", "province_id" => 25],
            ["id" => 1167, "name" => "كلاچاي", "province_id" => 25],
            ["id" => 1168, "name" => "كوچصفهان", "province_id" => 25],
            ["id" => 1169, "name" => "كومله", "province_id" => 25],
            ["id" => 1170, "name" => "كياشهر", "province_id" => 25],
            ["id" => 1171, "name" => "گوراب زرميخ", "province_id" => 25],
            ["id" => 1172, "name" => "لاهيجان", "province_id" => 25],
            ["id" => 1173, "name" => "لشت نشاء", "province_id" => 25],
            ["id" => 1174, "name" => "لنگرود", "province_id" => 25],
            ["id" => 1175, "name" => "لوشان", "province_id" => 25],
            ["id" => 1176, "name" => "لولمان", "province_id" => 25],
            ["id" => 1177, "name" => "لوندويل", "province_id" => 25],
            ["id" => 1178, "name" => "ليسار", "province_id" => 25],
            ["id" => 1179, "name" => "ماسال", "province_id" => 25],
            ["id" => 1180, "name" => "ماسوله", "province_id" => 25],
            ["id" => 1181, "name" => "مرجقل", "province_id" => 25],
            ["id" => 1182, "name" => "منجيل", "province_id" => 25],
            ["id" => 1183, "name" => "واجارگاه", "province_id" => 25],
            ["id" => 1184, "name" => "هشتپر", "province_id" => 25],

        ];

        City::upsert($data, ["id"], ["name", "province_id"]);
    }
}
